<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>InscripcionCurso</RootNamespace>
    <StartupObject>InscripcionCurso.Program</StartupObject>

    <!-- Requisito obligatorio de la práctica -->
    <OptionStrict>On</OptionStrict>
    <OptionExplicit>On</OptionExplicit>

    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

</Project>
