<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>EditorEnriquecido</RootNamespace>
    <AssemblyName>EditorEnriquecido</AssemblyName>
    <OptionStrict>On</OptionStrict>
    <OptionExplicit>On</OptionExplicit>
    <Nullable>disable</Nullable>
    <ImplicitUsings>false</ImplicitUsings>
  </PropertyGroup>

</Project>
