<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>RegistroApp</RootNamespace>
    <AssemblyName>RegistroApp</AssemblyName>

    <!-- Requisito obligatorio de la práctica -->
    <OptionStrict>On</OptionStrict>
    <OptionExplicit>On</OptionExplicit>

    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

</Project>
